name: Test thing

on:
  pull_request_target:
    types: [closed]
    branches:
      - test

jobs:
  test:
    name: Test
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Do Something lol
        run: echo "Nice!"
